### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by KirbyRedius** [Tera2Space/TeraTTS#3]
Ошибки при запуске:

```
Traceback (most recent call last):
  File "s:\my_folder\main.py", line 16, in <module>
    accentizer.load(omograph_model_size='big_poetry', use_dictionary=True) 
  File "S:\python\Lib\site-packages\ruaccent\ruaccent.py", line 78, in load
    self.omograph_model.load(
  File "S:\python\Lib\site-packages\ruaccent\omograph_model.py", line 11, in load
    self.tokenizer = AutoTokenizer.from_pretrained(path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\python\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 754, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\python\Lib\site-packages\transformers\tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "S:\python\Lib\site-packages\transformers\tokenization_utils_base.py", line 1886, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\python\Lib\site-packages\transformers\tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\python\Lib\site-packages\transformers\models\bert\tokenization_bert.py", line 213, in __init__
    if not os.path.isfile(vocab_file):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Код взят с примера:
```
from RUTTS import TTS

# Создание модели TTS с указанным именем
# Примечание: Вы можете найти все модели по адресу https://huggingface.co/TeraTTS, включая модель GLADOS
tts = TTS("TeraTTS/natasha-g2p-vits", add_time_to_end=0.8)  # Вы можете настроить 'add_time_to_end' для продолжительности аудио

text = "Привет, мир!"
# Опционально: Предобработка текста (улучшает качество)
from ruaccent import RUAccent
accentizer = RUAccent(workdir="./model")

# Загрузка моделей акцентуации и словарей
# Доступны две модели: 'medium' (рекомендуется) и 'small'.
# Переменная 'dict_load_startup' управляет загрузкой словаря при запуске (больше памяти) или загрузкой его по мере необходимости во время выполнения (экономия памяти, но медленнее).
# Переменная disable_accent_dict отключает использование словаря (все ударения расставляет нейросеть). Данная функция экономит ОЗУ, по скорости работы сопоставима со всем словарём в ОЗУ.
accentizer.load(omograph_model_size='big_poetry', use_dictionary=True)

# Обработка текста с учетом ударений и буквы ё
text = accentizer.process_all(text)
print(f"Текст с ударениями и ё: {text}")

# Синтез речи
# 'length_scale' можно использовать для замедления аудио для лучшего звучания (по умолчанию 1.2, указано здесь для примера)
audio = tts(text, lenght_scale=1.2)  # Создать аудио. Можно добавить ударения, используя '+'
tts.play_audio(audio)  # Воспроизвести созданное аудио
tts.save_wav(audio, "./test.wav")  # Сохранить аудио в файл

# Создать аудио и сразу его воспроизвести
tts(text, play=True, lenght_scale=1.2)
```

**Comment by Tera2Space** [comment]
Проблема связанна с

**Comment by Tera2Space** [comment]
Проблемма связанная м дополнительным модулем для ударений, решим, пока просто удалите строки ```
from ruaccent import RUAccent
accentizer = RUAccent(workdir="./model")

# Загрузка моделей акцентуации и словарей
# Доступны две модели: 'medium' (рекомендуется) и 'small'.
# Переменная 'dict_load_startup' управляет загрузкой словаря при запуске (больше памяти) или загрузкой его по мере необходимости во время выполнения (экономия памяти, но медленнее).
# Переменная disable_accent_dict отключает использование словаря (все ударения расставляет нейросеть). Данная функция экономит ОЗУ, по скорости работы сопоставима со всем словарём в ОЗУ.
accentizer.load(omograph_model_size='big_poetry', use_dictionary=True)

# Обработка текста с учетом ударений и буквы ё
text = accentizer.process_all(text)
print(f"Текст с ударениями и ё: {text}")
```

**Comment by Tera2Space** [comment]
Проблема с акценунизаторм, решим, пока удалите строки 
from ruaccent import RUAccent
accentizer = RUAccent(workdir="./model") 
accentizer.load(omograph_model_size='big_poetry', use_dictionary=True)
text = accentizer.process_all(text)

**Comment by KirbyRedius** [comment]
Да, без акцента работает

**Comment by Tera2Space** [comment]
Что бы мы разобрались напиши pip list и скинь результат, а так же версию питона напиши

**Comment by KirbyRedius** [comment]
pip:
```
absl-py                      2.0.0
anyascii                     0.3.2
appdirs                      1.4.4
astor                        0.8.1
astunparse                   1.6.3
attrs                        23.1.0
Babel                        2.13.1
bcrypt                       4.0.1
beautifulsoup4               4.12.2
binapy                       0.7.0
bleach                       1.5.0
Brotli                       1.1.0
bs4                          0.0.1
cachetools                   3.1.1
CaptchaCracker               0.0.7
certifi                      2023.7.22
cffi                         1.16.0
cfscrape                     2.1.1
chardet                      3.0.4
charset-normalizer           3.3.0
cloudscraper                 1.2.71
colorama                     0.4.6
coloredlogs                  15.0.1
contourpy                    1.1.1
contractions                 0.1.73
cryptography                 41.0.4
curl-cffi                    0.5.9
cycler                       0.12.1
dateparser                   1.1.8
docopt                       0.6.2
filelock                     3.13.1
flatbuffers                  23.5.26
fonttools                    4.43.1
free-proxy                   1.1.1
fsspec                       2023.10.0
furl                         2.1.3
gast                         0.5.4
google-api-core              2.12.0
google-api-python-client     2.103.0
google-auth                  2.23.3
google-auth-httplib2         0.1.1
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
googleapis-common-protos     1.61.0
googletrans                  3.0.0
grpcio                       1.59.0
gruut                        2.3.4
gruut-ipa                    0.13.0
gruut-lang-en                2.0.0
gruut-lang-ru                2.0.0
h11                          0.9.0
h2                           3.2.0
h5py                         3.10.0
hpack                        3.0.0
hstspreload                  2023.1.1
html5lib                     0.9999999
httpcore                     0.9.1
httplib2                     0.22.0
httpx                        0.13.3
huggingface-hub              0.15.1
humanfriendly                10.0
hyperframe                   5.2.0
idna                         2.10
imap-tools                   1.4.0
importlib-metadata           6.8.0
install                      1.3.5
ja3requests                  1.0.1
joblib                       1.3.2
jsonlines                    1.2.0
jwskate                      0.10.0
keras                        2.14.0
kiwisolver                   1.4.5
libclang                     16.0.6
lxml                         4.9.3
Markdown                     3.5
MarkupSafe                   2.1.3
matplotlib                   3.8.0
ml-dtypes                    0.2.0
mpmath                       1.3.0
names                        0.3.0
networkx                     2.8.8
num2words                    0.5.13
numpy                        1.26.1
oauthlib                     3.2.2
onnxruntime                  1.16.2
opencv-python                4.8.1.78
opt-einsum                   3.3.0
orderedmultidict             1.0.1
outcome                      1.3.0
packaging                    23.2
paramiko                     3.3.1
Pillow                       9.5.0
pip                          23.3.1
protobuf                     4.24.4
psutil                       5.9.6
pyahocorasick                2.0.0
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pyee                         8.2.2
PyJWT                        2.8.0
PyNaCl                       1.5.0
pyparsing                    3.1.1
pyppeteer                    1.0.2
pyreadline3                  3.4.1
PySocks                      1.7.1
PyTempMail                   0.1
python-crfsuite              0.9.9
python-dateutil              2.8.2
pytz                         2023.3.post1
PyYAML                       6.0.1
regex                        2023.10.3
requests                     2.31.0
requests-file                1.5.1
requests-go                  0.5
requests_oauth2client        1.3.0
requests-oauthlib            1.3.1
requests-toolbelt            1.0.0
rfc3986                      1.5.0
rsa                          4.0
ruaccent                     1.5.4.1
RUTTS                        0.1.13
safetensors                  0.4.0
scikit-learn                 1.3.1
scipy                        1.11.3
selenium                     4.14.0
sentencepiece                0.1.99
setuptools                   68.2.2
six                          1.16.0
sklearn                      0.0.post10
sniffio                      1.3.0
sortedcontainers             2.4.0
sounddevice                  0.4.6
soupsieve                    2.5
sympy                        1.12
temporary-mail               1.6
tensorboard                  2.14.1
tensorboard-data-server      0.7.1
tensorflow                   2.14.0
tensorflow-estimator         2.14.0
tensorflow-intel             2.14.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.3.0
textsearch                   0.0.24
threadpoolctl                3.2.0
tldextract                   5.1.0
tls-client                   0.2.2
tok                          0.1.14
tokenizers                   0.13.3
tqdm                         4.66.1
transformers                 4.33.3
transliterate                1.10.2
trio                         0.22.2
trio-websocket               0.11.1
typing_extensions            4.8.0
tzdata                       2023.3
tzlocal                      5.2
uritemplate                  3.0.1
urllib3                      1.26.18
websocket-client             1.6.4
websockets                   10.4
Werkzeug                     3.0.0
wheel                        0.41.2
wrapt                        1.14.1
wsproto                      1.2.0
zipp                         3.17.0
```

Python 3.11.5

**Comment by Basisualiy** [comment]
Проблема в этой строке: 
accentizer = RUAccent(workdir="./model")
workdir= нет в методе __init__() решается переносом этого параметра в:
accentizer.load(workdir="./model", omograph_model_size='big_poetry', use_dictionary=True)
